SELECT generateschema();

INSERT INTO government VALUES(DEFAULT, 'G1');

INSERT INTO planet VALUES(DEFAULT, 'P1', 222.22, 1);

INSERT INTO commander VALUES(DEFAULT, 'C1', 'Harmless');
INSERT INTO commander VALUES(DEFAULT, 'C2', 'Poor');
INSERT INTO commander VALUES(DEFAULT, 'C3', 'Average');

INSERT INTO spacecraft VALUES(DEFAULT, 2, 'S1', 1);
INSERT INTO spacecraft VALUES(DEFAULT, 2, 'S2', 2);
INSERT INTO spacecraft VALUES(DEFAULT, 10, 'S3', 3);
INSERT INTO spacecraft VALUES(DEFAULT, 10, 'S4', 3);

INSERT INTO flight VALUES(1, 1, 1, 1, TO_DATE('17/12/2087', 'DD/MM/YYYY'));
INSERT INTO flight VALUES(2, 1, 1, 1, TO_DATE('17/12/2082', 'DD/MM/YYYY'));
INSERT INTO flight VALUES(3, 2, 1, 1, TO_DATE('17/12/2033', 'DD/MM/YYYY'));
INSERT INTO flight VALUES(4, 3, 1, 1, TO_DATE('17/12/2087', 'DD/MM/YYYY'));
INSERT INTO flight VALUES(5, 4, 1, 1, TO_DATE('17/12/2023', 'DD/MM/YYYY'));